Env: dev
Dev:
  CookieHost: coollocalhost.com
  CookieSecure: false
  HttpOnly: false
  CorsHost: http://www.coollocalhost.com:3000
  FrontUrl: http://www.coollocalhost.com:3000
Prod:
  CookieHost: workblok.com
  CookieSecure: true
  HttpOnly: true
  CorsHost: https://workblok.com:3000
  FrontUrl: https://workblok.com
IP: 0.0.0.0
Port: 8080
JwtKey: workblok258SECRETkey
Mail:
  User: workblokapp@gmail.com
  Pass: qsgy ufir hoii spst
  SmtpHost: smtp.gmail.com
  SmtpPort: 587
DB:
  Port: 3306
  Host: db
  User: root
  Pass: 1234
  DB: workblok
