Env: dev
Dev:
  CookieHost:  192.168.1.139
  CookieSecure: false
  HttpOnly: false
  CorsHost: http://192.168.1.139:3000
  FrontUrl: http://192.168.1.139:3000
Prod:
  CookieHost: workblok.com
  CookieSecure: true
  HttpOnly: true
  CorsHost: https://workblok.com:3000
  FrontUrl: https://workblok.com
IP: 0.0.0.0
Port: 8080
JwtKey: workblok258SECRETkey
Mail:
  User: workblokapp@gmail.com
  Pass: qsgy ufir hoii spst
  SmtpHost: smtp.gmail.com
  SmtpPort: 587
DB:
  Port: 3307
  Host: 127.0.0.1
  User: root
  Pass: 1234
  DB: workblok
