Env: dev
Dev:
  CookieHost: 192.168.0.111
  CookieSecure: false
  HttpOnly: false
  CorsHost: http://192.168.0.111:3000
Prod:
  CookieHost: workblok.com
  CookieSecure: true
  HttpOnly: true
  CorsHost: https://workblok.com:3000
IP: 0.0.0.0
Port: 8080
JwtKey: workblok258SECRETkey
Mail:
  User: workblok@gmail.com
  Pass: emaddwcfyqjexjum
  SmtpHost: smtp.gmail.com
  SmtpPort: 587
DB:
  Port: 3306
  Host: db
  User: root
  Pass: 1234
  DB: workblok
