Env: prod
Dev:
  CookieHost:  192.168.1.142
  CookieSecure: false
  CorsHost: http://192.168.1.142:3000
  FrontUrl: http://192.168.1.142:3000
  CookieHttpOnly: true
Prod:
  CookieHost: workblok.dviladev.com
  CookieSecure: true
  CookieHttpOnly: true
  CorsHost: https://workblok.dviladev.com:3001
  FrontUrl: https://workblok.dviladev.com
IP: 0.0.0.0
Port: 8080
JwtKey: workbloksecret
Mail:
  User: viladevapps@gmail.com
  SmtpHost: smtp.gmail.com
  SmtpPort: 587
  Enabled: true
  MailTypes:
    AccountActivation:
      Subject: Account activation
      Body: "You can access to this link to validate your Workblok account: %s/validate/%s/%s"
    PasswordReset:
      Subject: Password reset
      Body: "You can access to this link to change the password of your Workblok account: %s/reset-password/%s/%s"
DB:
  Port: 3306
  Host: db
  User: root
  Pass: 123456
  DB: workblok
