version: '3.3'

services:
  db:
      image: mysql:8.0
      restart: always
      ports:
        - "3308:3306"
      volumes:
        - db-volume:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_DATABASE: workblok
  api: 
    image: workblok-api:latest
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db
      
volumes:
  db-volume:
