services:
  db:
      image: mysql:8.0
      restart: always
      ports:
        - "3308:3306"
      volumes:
        - db-volume:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASS}
        MYSQL_DATABASE: workblok
  api: 
    image: workblok-api:latest
    environment:
      DB_PASS: ${DB_PASS}
      MAIL_PASS: ${MAIL_PASS}
      JWT_SECRET: ${JWT_SECRET}
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db
      
volumes:
  db-volume:
