// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"workblok/ent/predicate"
	"workblok/ent/user"
	"workblok/ent/verificationcode"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// VerificationCodeQuery is the builder for querying VerificationCode entities.
type VerificationCodeQuery struct {
	config
	ctx        *QueryContext
	order      []verificationcode.OrderOption
	inters     []Interceptor
	predicates []predicate.VerificationCode
	withUser   *UserQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the VerificationCodeQuery builder.
func (vcq *VerificationCodeQuery) Where(ps ...predicate.VerificationCode) *VerificationCodeQuery {
	vcq.predicates = append(vcq.predicates, ps...)
	return vcq
}

// Limit the number of records to be returned by this query.
func (vcq *VerificationCodeQuery) Limit(limit int) *VerificationCodeQuery {
	vcq.ctx.Limit = &limit
	return vcq
}

// Offset to start from.
func (vcq *VerificationCodeQuery) Offset(offset int) *VerificationCodeQuery {
	vcq.ctx.Offset = &offset
	return vcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (vcq *VerificationCodeQuery) Unique(unique bool) *VerificationCodeQuery {
	vcq.ctx.Unique = &unique
	return vcq
}

// Order specifies how the records should be ordered.
func (vcq *VerificationCodeQuery) Order(o ...verificationcode.OrderOption) *VerificationCodeQuery {
	vcq.order = append(vcq.order, o...)
	return vcq
}

// QueryUser chains the current query on the "user" edge.
func (vcq *VerificationCodeQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: vcq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := vcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := vcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(verificationcode.Table, verificationcode.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, verificationcode.UserTable, verificationcode.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(vcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first VerificationCode entity from the query.
// Returns a *NotFoundError when no VerificationCode was found.
func (vcq *VerificationCodeQuery) First(ctx context.Context) (*VerificationCode, error) {
	nodes, err := vcq.Limit(1).All(setContextOp(ctx, vcq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{verificationcode.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (vcq *VerificationCodeQuery) FirstX(ctx context.Context) *VerificationCode {
	node, err := vcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first VerificationCode ID from the query.
// Returns a *NotFoundError when no VerificationCode ID was found.
func (vcq *VerificationCodeQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = vcq.Limit(1).IDs(setContextOp(ctx, vcq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{verificationcode.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (vcq *VerificationCodeQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := vcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single VerificationCode entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one VerificationCode entity is found.
// Returns a *NotFoundError when no VerificationCode entities are found.
func (vcq *VerificationCodeQuery) Only(ctx context.Context) (*VerificationCode, error) {
	nodes, err := vcq.Limit(2).All(setContextOp(ctx, vcq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{verificationcode.Label}
	default:
		return nil, &NotSingularError{verificationcode.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (vcq *VerificationCodeQuery) OnlyX(ctx context.Context) *VerificationCode {
	node, err := vcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only VerificationCode ID in the query.
// Returns a *NotSingularError when more than one VerificationCode ID is found.
// Returns a *NotFoundError when no entities are found.
func (vcq *VerificationCodeQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = vcq.Limit(2).IDs(setContextOp(ctx, vcq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{verificationcode.Label}
	default:
		err = &NotSingularError{verificationcode.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (vcq *VerificationCodeQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := vcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of VerificationCodes.
func (vcq *VerificationCodeQuery) All(ctx context.Context) ([]*VerificationCode, error) {
	ctx = setContextOp(ctx, vcq.ctx, "All")
	if err := vcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*VerificationCode, *VerificationCodeQuery]()
	return withInterceptors[[]*VerificationCode](ctx, vcq, qr, vcq.inters)
}

// AllX is like All, but panics if an error occurs.
func (vcq *VerificationCodeQuery) AllX(ctx context.Context) []*VerificationCode {
	nodes, err := vcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of VerificationCode IDs.
func (vcq *VerificationCodeQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if vcq.ctx.Unique == nil && vcq.path != nil {
		vcq.Unique(true)
	}
	ctx = setContextOp(ctx, vcq.ctx, "IDs")
	if err = vcq.Select(verificationcode.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (vcq *VerificationCodeQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := vcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (vcq *VerificationCodeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, vcq.ctx, "Count")
	if err := vcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, vcq, querierCount[*VerificationCodeQuery](), vcq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (vcq *VerificationCodeQuery) CountX(ctx context.Context) int {
	count, err := vcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (vcq *VerificationCodeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, vcq.ctx, "Exist")
	switch _, err := vcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (vcq *VerificationCodeQuery) ExistX(ctx context.Context) bool {
	exist, err := vcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the VerificationCodeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (vcq *VerificationCodeQuery) Clone() *VerificationCodeQuery {
	if vcq == nil {
		return nil
	}
	return &VerificationCodeQuery{
		config:     vcq.config,
		ctx:        vcq.ctx.Clone(),
		order:      append([]verificationcode.OrderOption{}, vcq.order...),
		inters:     append([]Interceptor{}, vcq.inters...),
		predicates: append([]predicate.VerificationCode{}, vcq.predicates...),
		withUser:   vcq.withUser.Clone(),
		// clone intermediate query.
		sql:  vcq.sql.Clone(),
		path: vcq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (vcq *VerificationCodeQuery) WithUser(opts ...func(*UserQuery)) *VerificationCodeQuery {
	query := (&UserClient{config: vcq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	vcq.withUser = query
	return vcq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreationDate time.Time `json:"creationDate,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.VerificationCode.Query().
//		GroupBy(verificationcode.FieldCreationDate).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (vcq *VerificationCodeQuery) GroupBy(field string, fields ...string) *VerificationCodeGroupBy {
	vcq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &VerificationCodeGroupBy{build: vcq}
	grbuild.flds = &vcq.ctx.Fields
	grbuild.label = verificationcode.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreationDate time.Time `json:"creationDate,omitempty"`
//	}
//
//	client.VerificationCode.Query().
//		Select(verificationcode.FieldCreationDate).
//		Scan(ctx, &v)
func (vcq *VerificationCodeQuery) Select(fields ...string) *VerificationCodeSelect {
	vcq.ctx.Fields = append(vcq.ctx.Fields, fields...)
	sbuild := &VerificationCodeSelect{VerificationCodeQuery: vcq}
	sbuild.label = verificationcode.Label
	sbuild.flds, sbuild.scan = &vcq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a VerificationCodeSelect configured with the given aggregations.
func (vcq *VerificationCodeQuery) Aggregate(fns ...AggregateFunc) *VerificationCodeSelect {
	return vcq.Select().Aggregate(fns...)
}

func (vcq *VerificationCodeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range vcq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, vcq); err != nil {
				return err
			}
		}
	}
	for _, f := range vcq.ctx.Fields {
		if !verificationcode.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if vcq.path != nil {
		prev, err := vcq.path(ctx)
		if err != nil {
			return err
		}
		vcq.sql = prev
	}
	return nil
}

func (vcq *VerificationCodeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*VerificationCode, error) {
	var (
		nodes       = []*VerificationCode{}
		withFKs     = vcq.withFKs
		_spec       = vcq.querySpec()
		loadedTypes = [1]bool{
			vcq.withUser != nil,
		}
	)
	if vcq.withUser != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, verificationcode.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*VerificationCode).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &VerificationCode{config: vcq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, vcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := vcq.withUser; query != nil {
		if err := vcq.loadUser(ctx, query, nodes, nil,
			func(n *VerificationCode, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (vcq *VerificationCodeQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*VerificationCode, init func(*VerificationCode), assign func(*VerificationCode, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*VerificationCode)
	for i := range nodes {
		if nodes[i].user_codes == nil {
			continue
		}
		fk := *nodes[i].user_codes
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_codes" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (vcq *VerificationCodeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := vcq.querySpec()
	_spec.Node.Columns = vcq.ctx.Fields
	if len(vcq.ctx.Fields) > 0 {
		_spec.Unique = vcq.ctx.Unique != nil && *vcq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, vcq.driver, _spec)
}

func (vcq *VerificationCodeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(verificationcode.Table, verificationcode.Columns, sqlgraph.NewFieldSpec(verificationcode.FieldID, field.TypeUUID))
	_spec.From = vcq.sql
	if unique := vcq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if vcq.path != nil {
		_spec.Unique = true
	}
	if fields := vcq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, verificationcode.FieldID)
		for i := range fields {
			if fields[i] != verificationcode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := vcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := vcq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := vcq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := vcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (vcq *VerificationCodeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(vcq.driver.Dialect())
	t1 := builder.Table(verificationcode.Table)
	columns := vcq.ctx.Fields
	if len(columns) == 0 {
		columns = verificationcode.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if vcq.sql != nil {
		selector = vcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if vcq.ctx.Unique != nil && *vcq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range vcq.predicates {
		p(selector)
	}
	for _, p := range vcq.order {
		p(selector)
	}
	if offset := vcq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := vcq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// VerificationCodeGroupBy is the group-by builder for VerificationCode entities.
type VerificationCodeGroupBy struct {
	selector
	build *VerificationCodeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (vcgb *VerificationCodeGroupBy) Aggregate(fns ...AggregateFunc) *VerificationCodeGroupBy {
	vcgb.fns = append(vcgb.fns, fns...)
	return vcgb
}

// Scan applies the selector query and scans the result into the given value.
func (vcgb *VerificationCodeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, vcgb.build.ctx, "GroupBy")
	if err := vcgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VerificationCodeQuery, *VerificationCodeGroupBy](ctx, vcgb.build, vcgb, vcgb.build.inters, v)
}

func (vcgb *VerificationCodeGroupBy) sqlScan(ctx context.Context, root *VerificationCodeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(vcgb.fns))
	for _, fn := range vcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*vcgb.flds)+len(vcgb.fns))
		for _, f := range *vcgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*vcgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vcgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// VerificationCodeSelect is the builder for selecting fields of VerificationCode entities.
type VerificationCodeSelect struct {
	*VerificationCodeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (vcs *VerificationCodeSelect) Aggregate(fns ...AggregateFunc) *VerificationCodeSelect {
	vcs.fns = append(vcs.fns, fns...)
	return vcs
}

// Scan applies the selector query and scans the result into the given value.
func (vcs *VerificationCodeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, vcs.ctx, "Select")
	if err := vcs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VerificationCodeQuery, *VerificationCodeSelect](ctx, vcs.VerificationCodeQuery, vcs, vcs.inters, v)
}

func (vcs *VerificationCodeSelect) sqlScan(ctx context.Context, root *VerificationCodeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(vcs.fns))
	for _, fn := range vcs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*vcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
