// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"workblok/ent/predicate"
	"workblok/ent/verificationcode"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// VerificationCodeDelete is the builder for deleting a VerificationCode entity.
type VerificationCodeDelete struct {
	config
	hooks    []Hook
	mutation *VerificationCodeMutation
}

// Where appends a list predicates to the VerificationCodeDelete builder.
func (vcd *VerificationCodeDelete) Where(ps ...predicate.VerificationCode) *VerificationCodeDelete {
	vcd.mutation.Where(ps...)
	return vcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (vcd *VerificationCodeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, VerificationCodeMutation](ctx, vcd.sqlExec, vcd.mutation, vcd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (vcd *VerificationCodeDelete) ExecX(ctx context.Context) int {
	n, err := vcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (vcd *VerificationCodeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(verificationcode.Table, sqlgraph.NewFieldSpec(verificationcode.FieldID, field.TypeUUID))
	if ps := vcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, vcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	vcd.mutation.done = true
	return affected, err
}

// VerificationCodeDeleteOne is the builder for deleting a single VerificationCode entity.
type VerificationCodeDeleteOne struct {
	vcd *VerificationCodeDelete
}

// Where appends a list predicates to the VerificationCodeDelete builder.
func (vcdo *VerificationCodeDeleteOne) Where(ps ...predicate.VerificationCode) *VerificationCodeDeleteOne {
	vcdo.vcd.mutation.Where(ps...)
	return vcdo
}

// Exec executes the deletion query.
func (vcdo *VerificationCodeDeleteOne) Exec(ctx context.Context) error {
	n, err := vcdo.vcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{verificationcode.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (vcdo *VerificationCodeDeleteOne) ExecX(ctx context.Context) {
	if err := vcdo.Exec(ctx); err != nil {
		panic(err)
	}
}
